# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /data/data/com.termux/files/usr/bin/sh

# The CMake executable.
CMAKE_COMMAND = /data/data/com.termux/files/usr/bin/cmake

# The command to remove a file.
RM = /data/data/com.termux/files/usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data/com.termux/files/home/katane

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data/com.termux/files/home/katane

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/data/data/com.termux/files/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/data/data/com.termux/files/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/katane/CMakeFiles /data/data/com.termux/files/home/katane//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/katane/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named katane

# Build rule for target.
katane: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 katane
.PHONY : katane

# fast build rule for target.
katane/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/build
.PHONY : katane/fast

src/Array.o: src/Array.c.o
.PHONY : src/Array.o

# target to build an object file
src/Array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Array.c.o
.PHONY : src/Array.c.o

src/Array.i: src/Array.c.i
.PHONY : src/Array.i

# target to preprocess a source file
src/Array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Array.c.i
.PHONY : src/Array.c.i

src/Array.s: src/Array.c.s
.PHONY : src/Array.s

# target to generate assembly for a file
src/Array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Array.c.s
.PHONY : src/Array.c.s

src/Chunk.o: src/Chunk.c.o
.PHONY : src/Chunk.o

# target to build an object file
src/Chunk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Chunk.c.o
.PHONY : src/Chunk.c.o

src/Chunk.i: src/Chunk.c.i
.PHONY : src/Chunk.i

# target to preprocess a source file
src/Chunk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Chunk.c.i
.PHONY : src/Chunk.c.i

src/Chunk.s: src/Chunk.c.s
.PHONY : src/Chunk.s

# target to generate assembly for a file
src/Chunk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Chunk.c.s
.PHONY : src/Chunk.c.s

src/Compiler.o: src/Compiler.c.o
.PHONY : src/Compiler.o

# target to build an object file
src/Compiler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Compiler.c.o
.PHONY : src/Compiler.c.o

src/Compiler.i: src/Compiler.c.i
.PHONY : src/Compiler.i

# target to preprocess a source file
src/Compiler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Compiler.c.i
.PHONY : src/Compiler.c.i

src/Compiler.s: src/Compiler.c.s
.PHONY : src/Compiler.s

# target to generate assembly for a file
src/Compiler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Compiler.c.s
.PHONY : src/Compiler.c.s

src/Debug.o: src/Debug.c.o
.PHONY : src/Debug.o

# target to build an object file
src/Debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Debug.c.o
.PHONY : src/Debug.c.o

src/Debug.i: src/Debug.c.i
.PHONY : src/Debug.i

# target to preprocess a source file
src/Debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Debug.c.i
.PHONY : src/Debug.c.i

src/Debug.s: src/Debug.c.s
.PHONY : src/Debug.s

# target to generate assembly for a file
src/Debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Debug.c.s
.PHONY : src/Debug.c.s

src/Exceptions.o: src/Exceptions.c.o
.PHONY : src/Exceptions.o

# target to build an object file
src/Exceptions.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Exceptions.c.o
.PHONY : src/Exceptions.c.o

src/Exceptions.i: src/Exceptions.c.i
.PHONY : src/Exceptions.i

# target to preprocess a source file
src/Exceptions.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Exceptions.c.i
.PHONY : src/Exceptions.c.i

src/Exceptions.s: src/Exceptions.c.s
.PHONY : src/Exceptions.s

# target to generate assembly for a file
src/Exceptions.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Exceptions.c.s
.PHONY : src/Exceptions.c.s

src/HashMap.o: src/HashMap.c.o
.PHONY : src/HashMap.o

# target to build an object file
src/HashMap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/HashMap.c.o
.PHONY : src/HashMap.c.o

src/HashMap.i: src/HashMap.c.i
.PHONY : src/HashMap.i

# target to preprocess a source file
src/HashMap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/HashMap.c.i
.PHONY : src/HashMap.c.i

src/HashMap.s: src/HashMap.c.s
.PHONY : src/HashMap.s

# target to generate assembly for a file
src/HashMap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/HashMap.c.s
.PHONY : src/HashMap.c.s

src/Main.o: src/Main.c.o
.PHONY : src/Main.o

# target to build an object file
src/Main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Main.c.o
.PHONY : src/Main.c.o

src/Main.i: src/Main.c.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Main.c.i
.PHONY : src/Main.c.i

src/Main.s: src/Main.c.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Main.c.s
.PHONY : src/Main.c.s

src/Map.o: src/Map.c.o
.PHONY : src/Map.o

# target to build an object file
src/Map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Map.c.o
.PHONY : src/Map.c.o

src/Map.i: src/Map.c.i
.PHONY : src/Map.i

# target to preprocess a source file
src/Map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Map.c.i
.PHONY : src/Map.c.i

src/Map.s: src/Map.c.s
.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Map.c.s
.PHONY : src/Map.c.s

src/Memory.o: src/Memory.c.o
.PHONY : src/Memory.o

# target to build an object file
src/Memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Memory.c.o
.PHONY : src/Memory.c.o

src/Memory.i: src/Memory.c.i
.PHONY : src/Memory.i

# target to preprocess a source file
src/Memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Memory.c.i
.PHONY : src/Memory.c.i

src/Memory.s: src/Memory.c.s
.PHONY : src/Memory.s

# target to generate assembly for a file
src/Memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Memory.c.s
.PHONY : src/Memory.c.s

src/Native.o: src/Native.c.o
.PHONY : src/Native.o

# target to build an object file
src/Native.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Native.c.o
.PHONY : src/Native.c.o

src/Native.i: src/Native.c.i
.PHONY : src/Native.i

# target to preprocess a source file
src/Native.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Native.c.i
.PHONY : src/Native.c.i

src/Native.s: src/Native.c.s
.PHONY : src/Native.s

# target to generate assembly for a file
src/Native.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Native.c.s
.PHONY : src/Native.c.s

src/Object.o: src/Object.c.o
.PHONY : src/Object.o

# target to build an object file
src/Object.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Object.c.o
.PHONY : src/Object.c.o

src/Object.i: src/Object.c.i
.PHONY : src/Object.i

# target to preprocess a source file
src/Object.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Object.c.i
.PHONY : src/Object.c.i

src/Object.s: src/Object.c.s
.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Object.c.s
.PHONY : src/Object.c.s

src/Platform.o: src/Platform.c.o
.PHONY : src/Platform.o

# target to build an object file
src/Platform.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Platform.c.o
.PHONY : src/Platform.c.o

src/Platform.i: src/Platform.c.i
.PHONY : src/Platform.i

# target to preprocess a source file
src/Platform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Platform.c.i
.PHONY : src/Platform.c.i

src/Platform.s: src/Platform.c.s
.PHONY : src/Platform.s

# target to generate assembly for a file
src/Platform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Platform.c.s
.PHONY : src/Platform.c.s

src/Primitives.o: src/Primitives.c.o
.PHONY : src/Primitives.o

# target to build an object file
src/Primitives.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Primitives.c.o
.PHONY : src/Primitives.c.o

src/Primitives.i: src/Primitives.c.i
.PHONY : src/Primitives.i

# target to preprocess a source file
src/Primitives.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Primitives.c.i
.PHONY : src/Primitives.c.i

src/Primitives.s: src/Primitives.c.s
.PHONY : src/Primitives.s

# target to generate assembly for a file
src/Primitives.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Primitives.c.s
.PHONY : src/Primitives.c.s

src/Scanner.o: src/Scanner.c.o
.PHONY : src/Scanner.o

# target to build an object file
src/Scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Scanner.c.o
.PHONY : src/Scanner.c.o

src/Scanner.i: src/Scanner.c.i
.PHONY : src/Scanner.i

# target to preprocess a source file
src/Scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Scanner.c.i
.PHONY : src/Scanner.c.i

src/Scanner.s: src/Scanner.c.s
.PHONY : src/Scanner.s

# target to generate assembly for a file
src/Scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Scanner.c.s
.PHONY : src/Scanner.c.s

src/Table.o: src/Table.c.o
.PHONY : src/Table.o

# target to build an object file
src/Table.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Table.c.o
.PHONY : src/Table.c.o

src/Table.i: src/Table.c.i
.PHONY : src/Table.i

# target to preprocess a source file
src/Table.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Table.c.i
.PHONY : src/Table.c.i

src/Table.s: src/Table.c.s
.PHONY : src/Table.s

# target to generate assembly for a file
src/Table.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Table.c.s
.PHONY : src/Table.c.s

src/Tutorial.o: src/Tutorial.c.o
.PHONY : src/Tutorial.o

# target to build an object file
src/Tutorial.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Tutorial.c.o
.PHONY : src/Tutorial.c.o

src/Tutorial.i: src/Tutorial.c.i
.PHONY : src/Tutorial.i

# target to preprocess a source file
src/Tutorial.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Tutorial.c.i
.PHONY : src/Tutorial.c.i

src/Tutorial.s: src/Tutorial.c.s
.PHONY : src/Tutorial.s

# target to generate assembly for a file
src/Tutorial.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Tutorial.c.s
.PHONY : src/Tutorial.c.s

src/TypeDescriptor.o: src/TypeDescriptor.c.o
.PHONY : src/TypeDescriptor.o

# target to build an object file
src/TypeDescriptor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/TypeDescriptor.c.o
.PHONY : src/TypeDescriptor.c.o

src/TypeDescriptor.i: src/TypeDescriptor.c.i
.PHONY : src/TypeDescriptor.i

# target to preprocess a source file
src/TypeDescriptor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/TypeDescriptor.c.i
.PHONY : src/TypeDescriptor.c.i

src/TypeDescriptor.s: src/TypeDescriptor.c.s
.PHONY : src/TypeDescriptor.s

# target to generate assembly for a file
src/TypeDescriptor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/TypeDescriptor.c.s
.PHONY : src/TypeDescriptor.c.s

src/Utf8.o: src/Utf8.c.o
.PHONY : src/Utf8.o

# target to build an object file
src/Utf8.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Utf8.c.o
.PHONY : src/Utf8.c.o

src/Utf8.i: src/Utf8.c.i
.PHONY : src/Utf8.i

# target to preprocess a source file
src/Utf8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Utf8.c.i
.PHONY : src/Utf8.c.i

src/Utf8.s: src/Utf8.c.s
.PHONY : src/Utf8.s

# target to generate assembly for a file
src/Utf8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Utf8.c.s
.PHONY : src/Utf8.c.s

src/Utilities.o: src/Utilities.c.o
.PHONY : src/Utilities.o

# target to build an object file
src/Utilities.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Utilities.c.o
.PHONY : src/Utilities.c.o

src/Utilities.i: src/Utilities.c.i
.PHONY : src/Utilities.i

# target to preprocess a source file
src/Utilities.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Utilities.c.i
.PHONY : src/Utilities.c.i

src/Utilities.s: src/Utilities.c.s
.PHONY : src/Utilities.s

# target to generate assembly for a file
src/Utilities.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Utilities.c.s
.PHONY : src/Utilities.c.s

src/VM.o: src/VM.c.o
.PHONY : src/VM.o

# target to build an object file
src/VM.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/VM.c.o
.PHONY : src/VM.c.o

src/VM.i: src/VM.c.i
.PHONY : src/VM.i

# target to preprocess a source file
src/VM.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/VM.c.i
.PHONY : src/VM.c.i

src/VM.s: src/VM.c.s
.PHONY : src/VM.s

# target to generate assembly for a file
src/VM.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/VM.c.s
.PHONY : src/VM.c.s

src/Value.o: src/Value.c.o
.PHONY : src/Value.o

# target to build an object file
src/Value.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Value.c.o
.PHONY : src/Value.c.o

src/Value.i: src/Value.c.i
.PHONY : src/Value.i

# target to preprocess a source file
src/Value.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Value.c.i
.PHONY : src/Value.c.i

src/Value.s: src/Value.c.s
.PHONY : src/Value.s

# target to generate assembly for a file
src/Value.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/katane.dir/build.make CMakeFiles/katane.dir/src/Value.c.s
.PHONY : src/Value.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... katane"
	@echo "... src/Array.o"
	@echo "... src/Array.i"
	@echo "... src/Array.s"
	@echo "... src/Chunk.o"
	@echo "... src/Chunk.i"
	@echo "... src/Chunk.s"
	@echo "... src/Compiler.o"
	@echo "... src/Compiler.i"
	@echo "... src/Compiler.s"
	@echo "... src/Debug.o"
	@echo "... src/Debug.i"
	@echo "... src/Debug.s"
	@echo "... src/Exceptions.o"
	@echo "... src/Exceptions.i"
	@echo "... src/Exceptions.s"
	@echo "... src/HashMap.o"
	@echo "... src/HashMap.i"
	@echo "... src/HashMap.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/Memory.o"
	@echo "... src/Memory.i"
	@echo "... src/Memory.s"
	@echo "... src/Native.o"
	@echo "... src/Native.i"
	@echo "... src/Native.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/Platform.o"
	@echo "... src/Platform.i"
	@echo "... src/Platform.s"
	@echo "... src/Primitives.o"
	@echo "... src/Primitives.i"
	@echo "... src/Primitives.s"
	@echo "... src/Scanner.o"
	@echo "... src/Scanner.i"
	@echo "... src/Scanner.s"
	@echo "... src/Table.o"
	@echo "... src/Table.i"
	@echo "... src/Table.s"
	@echo "... src/Tutorial.o"
	@echo "... src/Tutorial.i"
	@echo "... src/Tutorial.s"
	@echo "... src/TypeDescriptor.o"
	@echo "... src/TypeDescriptor.i"
	@echo "... src/TypeDescriptor.s"
	@echo "... src/Utf8.o"
	@echo "... src/Utf8.i"
	@echo "... src/Utf8.s"
	@echo "... src/Utilities.o"
	@echo "... src/Utilities.i"
	@echo "... src/Utilities.s"
	@echo "... src/VM.o"
	@echo "... src/VM.i"
	@echo "... src/VM.s"
	@echo "... src/Value.o"
	@echo "... src/Value.i"
	@echo "... src/Value.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

