#ifndef KATANE_CONFIG_H
#define KATANE_CONFIG_H

#define KATANE_EXTENSION ".ktn"
#define KATANE_VERSION "0.1.0"
#define LIBRARY_DIRECTORY "libs"
#define LIBRARY_DIRECTORY_INDEX "main"
#define PACKAGES_DIRECTORY "apps"
#define LOCAL_PACKAGES_DIRECTORY ".katane"
#define LOCAL_EXT_DIRECTORY "/bin"
#define LOCAL_SRC_DIRECTORY "/libs"

#define DEBUG_MODE 0

#define MAX_USING_CASES 256
#define MAX_FUNCTION_PARAMETERS 255
#define MAX_CASES 256
#define MAX_GENERICS 8
#define MAX_TYPE_UNION 8
#define MAX_TYPED_PARAMS 256
#define MAX_TYPED_GLOBALS 1024
#define MAX_CLASS_PROPERTIES 256
#define MAX_BREAK_JUMPS 256
#define MAX_FRAMES 1000
#define MAX_ERRORS 256
#define MAX_INTERPOLATION_NESTING 8
#define MAX_EXCEPTION_HANDLERS 16

//#define EXPERIMENTAL_IMPLICIT_THIS
#define NAN_BOXING

#endif